source 'http://rubygems.org' do
    
    group :external_test_gems do
        gem 'rspec'
        gem 'factory_bot'
        gem 'faker'
        gem 'dotenv'
    end
end

source 'https://MVZrB-4Zc1vt8x1SeDnEYfymn3cBjVWVo@gem.fury.io/seekr/' do
    
    group :internal_test_gems do
        gem 'hi_httparty'
    end
end
